"""removed contact info from student and teachers

Revision ID: 8b70d5835a59
Revises: 7fb4f4034692
Create Date: 2024-09-27 15:38:02.371471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b70d5835a59'
down_revision = '7fb4f4034692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('parent_contact')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_contact', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
